// <auto-generated />
namespace CarService.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Wikiego_testowa_migracja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Wikiego_testowa_migracja));
        
        string IMigrationMetadata.Id
        {
            get { return "201801231605019_Wikiego_testowa_migracja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
